build "core init test/glucose"

create_boot_directory

install_config {
<config>
	<parent-provides>
		<service name="ROM"/>
		<service name="RAM"/>
		<service name="IRQ"/>
		<service name="IO_MEM"/>
		<service name="IO_PORT"/>
		<service name="CAP"/>
		<service name="PD"/>
		<service name="RM"/>
		<service name="CPU"/>
		<service name="LOG"/>
		<service name="SIGNAL"/>
	</parent-provides>
	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>
	<start name="test-glucose">
		<resource name="RAM" quantum="32M"/>
		<config>
			<libc stdin="/dev/null" stdout="/dev/log" stderr="/dev/log">
				<vfs>
					<dir name="dev"> <log/> <null/> </dir>
					<rom name="Test.cnf"/>
				</vfs>
			</libc>
		</config>
	</start>
</config>
}

file copy -force [genode_dir]/repos/libports/src/test/glucose/Test.cnf bin/

build_boot_image {
	core init test-glucose
	ld.lib.so libc.lib.so
	libm.lib.so
	stdcxx.lib.so
	zlib.lib.so
	Test.cnf
}

append qemu_args " -nographic -m 64 "

run_genode_until {.*Okay.*} 20

exec rm bin/Test.cnf
