build "core init test/glucose drivers/timer"

create_boot_directory

file copy -force [genode_dir]/repos/libports/src/test/glucose/Test.cnf bin/

set filesize [exec stat -c "%s" bin/Test.cnf]

append config {
<config>
	<parent-provides>
		<service name="ROM"/>
		<service name="RAM"/>
		<service name="IRQ"/>
		<service name="IO_MEM"/>
		<service name="IO_PORT"/>
		<service name="CAP"/>
		<service name="PD"/>
		<service name="RM"/>
		<service name="CPU"/>
		<service name="LOG"/>
		<service name="SIGNAL"/>
	</parent-provides>
	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>
	<start name="timer">
		<resource name="RAM" quantum="1M"/>
		<provides>
			<service name="Timer"/>
		</provides>
	</start>
}

append config "
	<start name=\"test-glucose\">
		<resource name=\"RAM\" quantum=\"32M\"/>
		<config>
			<libc stdin=\"/dev/null\" stdout=\"/dev/log\" stderr=\"/dev/log\">
				<vfs>
					<dir name=\"dev\"> <log/> <null/> </dir>
					<rom name=\"Test.cnf\" size=\"$filesize\"/>
				</vfs>
			</libc>
		</config>
	</start>
</config>"

install_config $config

build_boot_image {
	core init test-glucose timer
	ld.lib.so libc.lib.so
	libm.lib.so
	stdcxx.lib.so
	zlib.lib.so
	Test.cnf
}

append qemu_args " -nographic -m 64 "

run_genode_until {.*Okay.*} 20

exec rm bin/Test.cnf
